version: "3.9"
services:
  app:
    container_name: app
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - mysql
  mysql:
    container_name: mysql
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_PASSWARD: pass
      MYSQL_DARABASE: playground
      MYSQL_USER: admin
    volumes:
      - ./docker/dev/mysql/data:/var/lib/mysql
